### ISSUE TITLE
thanks and promotion

### ISSUE THREAD

**Issue by wheelcomplex** [StalkR/dns-reverse-proxy#1]
Hi stalkr, thank you very much for written dns-reverse-proxy, it help me very much.

I forked and implemented a new feature called "race mode proxy", in this mode incoming query will send to multi-upstream dns servers(at the same time) and send the fastest/first response from upstream back to client.

With race mode the proxy got faster response time and handle failure upstream dns server gracefully, of course with more bandwidth usage.

Because my dirty hack to the source code I think it is not so good to create pull request for it, but it is a good ideal, right?

BTW: here is my code for reference https://github.com/wheelcomplex/dns-reverse-proxy

**Comment by StalkR** [comment]
Hi Yin,

Thanks for your email.
I'm glad you liked the project and extended it for your needs, that's why I
open sourced it!
While it's not a feature I'm interested in dns-reverse-proxy (so no need to
send a pull request), I agree it's a good idea to send concurrent requests
to have a faster dns resolver.
Best of luck with your project!

Cheers
