### ISSUE TITLE
Zone Transfer not working

### ISSUE THREAD

**Issue by TacitTactics** [StalkR/dns-reverse-proxy#14]
Please provide insights on how I can debug the zone transfer feature. The standard traffic is routed properly but when updating my DNS zone record. I have tested multiple ways. I am running on Ubuntu 22.10

**Comment by StalkR** [comment]
Hey, you can try using tcpdump/wireshark to analyze traffic it may give you an idea what's going wrong.

The code in dns-reverse-proxy is relying on https://github.com/miekg/dns so it may be a bug there (in fact I remember fixing zone transfer years ago when writing dns-reverse-proxy). You could try to isolate a test case with the dns library directly.

Sharing the domain name being used and giving access to others to do zone transfer would also be very useful so they can reproduce and investigate, otherwise without reproducer it's hard to investigate. If you do that I can take a look first for instance.

Cheers
