### ISSUE TITLE
route: host: support domain name not just IPs

### ISSUE THREAD

**Issue by winteraz** [StalkR/dns-reverse-proxy#6]
Usually domain names use subdomains in the NS record so I belive the route param should accept domains and resolve them at query time (e.g. -route .example.com.=ns-435.awsdns-54.com. )

**Comment by StalkR** [comment]
Yes, it could support it. In fact, I suppose it worked before but  fa5c77ac9ac04452e3b839c04d4967bd40181c53 to address #3 is too restrictive and should probably be relaxed.

Update: my bad, it never supported it.

**Comment by Xianic** [comment]
From testing it looks like it does support this currently (fa5c77ac9ac04452e3b839c04d4967bd40181c53) though it performs it's own DNS lookup for for the server on each query making it quite inefficient. I'll have a look at adding some caching to this.

**Comment by StalkR** [comment]
Indeed, it never supported it: the address (host:port) is passed as-is to the dns library https://godoc.org/github.com/miekg/dns#Client.Exchange which only supports IPs.

Adding domain support would not be without complexity:

- if domains are resolved before, one could argue they become stale and the server needs to be periodically restarted or handle refreshing them out of band
- if domains are resolved at query time, it brings additional latency and would be quite inefficient to do it every time, so a cache would be necessary

Since there hasn't been much demand for it since the request was filed 2017, and I don't need the feature myself (I only reverse proxy to local dns servers with static IPs), it's unlikely I ever work on it so I'm closing this. Feel free to reopen if you'd like to contribute and send a pull request.

Thanks!
